version: '3.8'

services:
  app:
    image: vrt-project-app
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        DOMAIN: localhost
        NETWORK_ID: 5777
        CHAIN_ID: 1337
        TESTNET_RPC: "http://localhost:8545"                        # https://testnet.andreaantonutti.it
        TESTNET_EXPLORER: "http://localhost:4000"                   # https://explorer.testnet.andreaantonutti.it
        IPFS_GATEWAY: "https://localhost:8080"                      # https://ipfs.andreaantonutti.it
        GRAPH_QUERY_BASE_URL: "http://localhost:8000"               # https://graph.andreaantonutti.it
        SUBGRAPH_NAME: "vrtproject"
        SECRET_COOKIE_PASSWORD: "z5c4kUE635h1Sgczml6aG7IdZisBf821"  # random at least 32 characters   
    ports:
      - 3000:3000