version: '3.8'

services:
  app:
    image: vrt-project-app
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        DOMAIN: localhost
        NETWORK_ID: 5777
        CHAIN_ID: 1337
        TESTNET_RPC: http://localhost:8545
        TESTNET_EXPLORER: http://localhost:4000
        IPFS_GATEWAY: https://localhost:8080
        GRAPH_QUERY_BASE_URL: http://localhost:8000
        SUBGRAPH_NAME: vrtproject
    ports:
      - 3000:3000